config/routes.rb
Rails.application.routes.draw do
  get "user_skills/:user_id" => "user_skills#new", as: :new_user_skills
  resources :users
  resources :skills, only: [:new, :create, :index]
  # resources :user_skills, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills
  has_many :users, through: :user_skills

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :category
end

app/models/user.rb
class User < ApplicationRecord
  #EMAIL_REGULAR_EXPRESSION =  /(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})/i

  validates_presence_of :name
  validates_presence_of :email

  #validates :email, format: { with: EMAIL_REGULAR_EXPRESSION }

  has_many :user_skills
  has_many :skills, through: :user_skills
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  private
  def skill_params
    params.require(:skill).permit(:name, :description, :category)
  end
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
  def new
    @skills = Skill.all
    @user_skill = UserSkill.new
  end

  def create

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.radio_button :category, "General" %> General
    <%= form.radio_button :category, "Engineering" %> Engineering
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/create.html.erb
<h1>Skills#create</h1>
<p>Find me in app/views/skills/create.html.erb</p>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Category</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.name %></td>
      <td><%= skill.description %></td>
      <td><%= skill.category %></td>
<!--      <td><%#= link_to 'Show', user %></td>-->
<!--      <td><%#= link_to 'Edit', edit_user_path(user) %></td>-->
<!--      <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

app/views/user_skills/new.html.erb
<h4>Add skills for user</h4>

<%#= form_with(model: @user_skill) do |form| %>
  <% skills = @skills.map { |s| [s.name, s.id] } %>
  <%= options_for_select(skills) %>
  <%#= form.select %>
<%# end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to "Add skills to this user", new_user_skills_path(@user.id) %>
<h2>User skills</h2>

<% if @user.user_skills.count > 0 %>
  <table>
    <tr>
      <td>
        Name
      </td>
      <td>
        Status
      </td>
    </tr>
    <% @user.user_skills.each do |user_skill| %>
      <tr>
        <td>
          <%= user_skill.skill.name %>
        </td>
        <td>
          <%= user_skill.status %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h4>No skills for this user yet</h4>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>